/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Details of a Stasis application
 */
@ApiModel(description = "Details of a Stasis application")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class Application {
  @SerializedName("name")
  private String name = null;

  @SerializedName("channel_ids")
  private List<String> channelIds = new ArrayList<>();

  @SerializedName("bridge_ids")
  private List<String> bridgeIds = new ArrayList<>();

  @SerializedName("endpoint_ids")
  private List<String> endpointIds = new ArrayList<>();

  @SerializedName("device_names")
  private List<String> deviceNames = new ArrayList<>();

  public Application name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of this application
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of this application")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Application channelIds(List<String> channelIds) {
    this.channelIds = channelIds;
    return this;
  }

  public Application addChannelIdsItem(String channelIdsItem) {
    this.channelIds.add(channelIdsItem);
    return this;
  }

   /**
   * Id&#39;s for channels subscribed to.
   * @return channelIds
  **/
  @ApiModelProperty(required = true, value = "Id's for channels subscribed to.")
  public List<String> getChannelIds() {
    return channelIds;
  }

  public void setChannelIds(List<String> channelIds) {
    this.channelIds = channelIds;
  }

  public Application bridgeIds(List<String> bridgeIds) {
    this.bridgeIds = bridgeIds;
    return this;
  }

  public Application addBridgeIdsItem(String bridgeIdsItem) {
    this.bridgeIds.add(bridgeIdsItem);
    return this;
  }

   /**
   * Id&#39;s for bridges subscribed to.
   * @return bridgeIds
  **/
  @ApiModelProperty(required = true, value = "Id's for bridges subscribed to.")
  public List<String> getBridgeIds() {
    return bridgeIds;
  }

  public void setBridgeIds(List<String> bridgeIds) {
    this.bridgeIds = bridgeIds;
  }

  public Application endpointIds(List<String> endpointIds) {
    this.endpointIds = endpointIds;
    return this;
  }

  public Application addEndpointIdsItem(String endpointIdsItem) {
    this.endpointIds.add(endpointIdsItem);
    return this;
  }

   /**
   * {tech}/{resource} for endpoints subscribed to.
   * @return endpointIds
  **/
  @ApiModelProperty(required = true, value = "{tech}/{resource} for endpoints subscribed to.")
  public List<String> getEndpointIds() {
    return endpointIds;
  }

  public void setEndpointIds(List<String> endpointIds) {
    this.endpointIds = endpointIds;
  }

  public Application deviceNames(List<String> deviceNames) {
    this.deviceNames = deviceNames;
    return this;
  }

  public Application addDeviceNamesItem(String deviceNamesItem) {
    this.deviceNames.add(deviceNamesItem);
    return this;
  }

   /**
   * Names of the devices subscribed to.
   * @return deviceNames
  **/
  @ApiModelProperty(required = true, value = "Names of the devices subscribed to.")
  public List<String> getDeviceNames() {
    return deviceNames;
  }

  public void setDeviceNames(List<String> deviceNames) {
    this.deviceNames = deviceNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.name, application.name) &&
        Objects.equals(this.channelIds, application.channelIds) &&
        Objects.equals(this.bridgeIds, application.bridgeIds) &&
        Objects.equals(this.endpointIds, application.endpointIds) &&
        Objects.equals(this.deviceNames, application.deviceNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, channelIds, bridgeIds, endpointIds, deviceNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    channelIds: ").append(toIndentedString(channelIds)).append("\n");
    sb.append("    bridgeIds: ").append(toIndentedString(bridgeIds)).append("\n");
    sb.append("    endpointIds: ").append(toIndentedString(endpointIds)).append("\n");
    sb.append("    deviceNames: ").append(toIndentedString(deviceNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

