/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Channel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Talking is no longer detected on the channel.
 */
@ApiModel(description = "Talking is no longer detected on the channel.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class ChannelTalkingFinished {
  @SerializedName("channel")
  private Channel channel = null;

  @SerializedName("duration")
  private Integer duration = null;

  public ChannelTalkingFinished channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The channel on which talking completed.
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "The channel on which talking completed.")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }

  public ChannelTalkingFinished duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * The length of time, in milliseconds, that talking was detected on the channel
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "The length of time, in milliseconds, that talking was detected on the channel")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelTalkingFinished channelTalkingFinished = (ChannelTalkingFinished) o;
    return Objects.equals(this.channel, channelTalkingFinished.channel) &&
        Objects.equals(this.duration, channelTalkingFinished.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, duration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelTalkingFinished {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

