/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Channel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A channel initiated a media hold.
 */
@ApiModel(description = "A channel initiated a media hold.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class ChannelHold {
  @SerializedName("channel")
  private Channel channel = null;

  @SerializedName("musicclass")
  private String musicclass = null;

  public ChannelHold channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The channel that initiated the hold event.
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "The channel that initiated the hold event.")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }

  public ChannelHold musicclass(String musicclass) {
    this.musicclass = musicclass;
    return this;
  }

   /**
   * The music on hold class that the initiator requested.
   * @return musicclass
  **/
  @ApiModelProperty(value = "The music on hold class that the initiator requested.")
  public String getMusicclass() {
    return musicclass;
  }

  public void setMusicclass(String musicclass) {
    this.musicclass = musicclass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelHold channelHold = (ChannelHold) o;
    return Objects.equals(this.channel, channelHold.channel) &&
        Objects.equals(this.musicclass, channelHold.musicclass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, musicclass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelHold {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    musicclass: ").append(toIndentedString(musicclass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

