/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Channel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Channel changed location in the dialplan.
 */
@ApiModel(description = "Channel changed location in the dialplan.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class ChannelDialplan {
  @SerializedName("channel")
  private Channel channel = null;

  @SerializedName("dialplan_app")
  private String dialplanApp = null;

  @SerializedName("dialplan_app_data")
  private String dialplanAppData = null;

  public ChannelDialplan channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The channel that changed dialplan location.
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "The channel that changed dialplan location.")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }

  public ChannelDialplan dialplanApp(String dialplanApp) {
    this.dialplanApp = dialplanApp;
    return this;
  }

   /**
   * The application about to be executed.
   * @return dialplanApp
  **/
  @ApiModelProperty(required = true, value = "The application about to be executed.")
  public String getDialplanApp() {
    return dialplanApp;
  }

  public void setDialplanApp(String dialplanApp) {
    this.dialplanApp = dialplanApp;
  }

  public ChannelDialplan dialplanAppData(String dialplanAppData) {
    this.dialplanAppData = dialplanAppData;
    return this;
  }

   /**
   * The data to be passed to the application.
   * @return dialplanAppData
  **/
  @ApiModelProperty(required = true, value = "The data to be passed to the application.")
  public String getDialplanAppData() {
    return dialplanAppData;
  }

  public void setDialplanAppData(String dialplanAppData) {
    this.dialplanAppData = dialplanAppData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelDialplan channelDialplan = (ChannelDialplan) o;
    return Objects.equals(this.channel, channelDialplan.channel) &&
        Objects.equals(this.dialplanApp, channelDialplan.dialplanApp) &&
        Objects.equals(this.dialplanAppData, channelDialplan.dialplanAppData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, dialplanApp, dialplanAppData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelDialplan {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    dialplanApp: ").append(toIndentedString(dialplanApp)).append("\n");
    sb.append("    dialplanAppData: ").append(toIndentedString(dialplanAppData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

