/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Channel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Notification that a channel has been destroyed.
 */
@ApiModel(description = "Notification that a channel has been destroyed.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class ChannelDestroyed {
  @SerializedName("cause")
  private Integer cause = null;

  @SerializedName("cause_txt")
  private String causeTxt = null;

  @SerializedName("channel")
  private Channel channel = null;

  public ChannelDestroyed cause(Integer cause) {
    this.cause = cause;
    return this;
  }

   /**
   * Integer representation of the cause of the hangup
   * @return cause
  **/
  @ApiModelProperty(required = true, value = "Integer representation of the cause of the hangup")
  public Integer getCause() {
    return cause;
  }

  public void setCause(Integer cause) {
    this.cause = cause;
  }

  public ChannelDestroyed causeTxt(String causeTxt) {
    this.causeTxt = causeTxt;
    return this;
  }

   /**
   * Text representation of the cause of the hangup
   * @return causeTxt
  **/
  @ApiModelProperty(required = true, value = "Text representation of the cause of the hangup")
  public String getCauseTxt() {
    return causeTxt;
  }

  public void setCauseTxt(String causeTxt) {
    this.causeTxt = causeTxt;
  }

  public ChannelDestroyed channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelDestroyed channelDestroyed = (ChannelDestroyed) o;
    return Objects.equals(this.cause, channelDestroyed.cause) &&
        Objects.equals(this.causeTxt, channelDestroyed.causeTxt) &&
        Objects.equals(this.channel, channelDestroyed.channel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cause, causeTxt, channel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelDestroyed {\n");
    
    sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
    sb.append("    causeTxt: ").append(toIndentedString(causeTxt)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

