/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Bridge;
import com.github.jasterisk.model.Channel;
import com.github.jasterisk.model.Endpoint;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * User-generated event with additional user-defined fields in the object.
 */
@ApiModel(description = "User-generated event with additional user-defined fields in the object.")

public class ChannelUserevent {
  @SerializedName("eventname")
  private String eventname = null;

  @SerializedName("channel")
  private Channel channel = null;

  @SerializedName("bridge")
  private Bridge bridge = null;

  @SerializedName("endpoint")
  private Endpoint endpoint = null;

  @SerializedName("userevent")
  private String userevent = null;

  public ChannelUserevent eventname(String eventname) {
    this.eventname = eventname;
    return this;
  }

   /**
   * The name of the user event.
   * @return eventname
  **/
  @ApiModelProperty(required = true, value = "The name of the user event.")
  public String getEventname() {
    return eventname;
  }

  public void setEventname(String eventname) {
    this.eventname = eventname;
  }

  public ChannelUserevent channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * A channel that is signaled with the user event.
   * @return channel
  **/
  @ApiModelProperty(value = "A channel that is signaled with the user event.")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }

  public ChannelUserevent bridge(Bridge bridge) {
    this.bridge = bridge;
    return this;
  }

   /**
   * A bridge that is signaled with the user event.
   * @return bridge
  **/
  @ApiModelProperty(value = "A bridge that is signaled with the user event.")
  public Bridge getBridge() {
    return bridge;
  }

  public void setBridge(Bridge bridge) {
    this.bridge = bridge;
  }

  public ChannelUserevent endpoint(Endpoint endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * A endpoint that is signaled with the user event.
   * @return endpoint
  **/
  @ApiModelProperty(value = "A endpoint that is signaled with the user event.")
  public Endpoint getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(Endpoint endpoint) {
    this.endpoint = endpoint;
  }

  public ChannelUserevent userevent(String userevent) {
    this.userevent = userevent;
    return this;
  }

   /**
   * Custom Userevent data
   * @return userevent
  **/
  @ApiModelProperty(required = true, value = "Custom Userevent data")
  public String getUserevent() {
    return userevent;
  }

  public void setUserevent(String userevent) {
    this.userevent = userevent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelUserevent channelUserevent = (ChannelUserevent) o;
    return Objects.equals(this.eventname, channelUserevent.eventname) &&
        Objects.equals(this.channel, channelUserevent.channel) &&
        Objects.equals(this.bridge, channelUserevent.bridge) &&
        Objects.equals(this.endpoint, channelUserevent.endpoint) &&
        Objects.equals(this.userevent, channelUserevent.userevent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventname, channel, bridge, endpoint, userevent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelUserevent {\n");
    
    sb.append("    eventname: ").append(toIndentedString(eventname)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    bridge: ").append(toIndentedString(bridge)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    userevent: ").append(toIndentedString(userevent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

