/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.ConfigTuple;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A configuration object containing ConfigTuples.
 */
@ApiModel(description = "A configuration object containing ConfigTuples.")

public class ConfigObject {
  @SerializedName("fields")
  private List<ConfigTuple> fields = new ArrayList<>();

  public ConfigObject fields(List<ConfigTuple> fields) {
    this.fields = fields;
    return this;
  }

  public ConfigObject addFieldsItem(ConfigTuple fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Configuration tuples.
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "Configuration tuples.")
  public List<ConfigTuple> getFields() {
    return fields;
  }

  public void setFields(List<ConfigTuple> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigObject configObject = (ConfigObject) o;
    return Objects.equals(this.fields, configObject.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigObject {\n");
    
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

