/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A key/value pair that makes up part of a configuration object.
 */
@ApiModel(description = "A key/value pair that makes up part of a configuration object.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class ConfigTuple {
  @SerializedName("attribute")
  private String attribute = null;

  @SerializedName("value")
  private String value = null;

  public ConfigTuple attribute(String attribute) {
    this.attribute = attribute;
    return this;
  }

   /**
   * A configuration object attribute.
   * @return attribute
  **/
  @ApiModelProperty(required = true, value = "A configuration object attribute.")
  public String getAttribute() {
    return attribute;
  }

  public void setAttribute(String attribute) {
    this.attribute = attribute;
  }

  public ConfigTuple value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value for the attribute.
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The value for the attribute.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigTuple configTuple = (ConfigTuple) o;
    return Objects.equals(this.attribute, configTuple.attribute) &&
        Objects.equals(this.value, configTuple.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attribute, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigTuple {\n");
    
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

