/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.SetId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Info about Asterisk configuration
 */
@ApiModel(description = "Info about Asterisk configuration")

public class ConfigInfo {
  @SerializedName("name")
  private String name = null;

  @SerializedName("default_language")
  private String defaultLanguage = null;

  @SerializedName("max_channels")
  private Integer maxChannels = null;

  @SerializedName("max_open_files")
  private Integer maxOpenFiles = null;

  @SerializedName("max_load")
  private Double maxLoad = null;

  @SerializedName("setid")
  private SetId setid = null;

  public ConfigInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Asterisk system name.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Asterisk system name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ConfigInfo defaultLanguage(String defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
    return this;
  }

   /**
   * Default language for media playback.
   * @return defaultLanguage
  **/
  @ApiModelProperty(required = true, value = "Default language for media playback.")
  public String getDefaultLanguage() {
    return defaultLanguage;
  }

  public void setDefaultLanguage(String defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
  }

  public ConfigInfo maxChannels(Integer maxChannels) {
    this.maxChannels = maxChannels;
    return this;
  }

   /**
   * Maximum number of simultaneous channels.
   * @return maxChannels
  **/
  @ApiModelProperty(value = "Maximum number of simultaneous channels.")
  public Integer getMaxChannels() {
    return maxChannels;
  }

  public void setMaxChannels(Integer maxChannels) {
    this.maxChannels = maxChannels;
  }

  public ConfigInfo maxOpenFiles(Integer maxOpenFiles) {
    this.maxOpenFiles = maxOpenFiles;
    return this;
  }

   /**
   * Maximum number of open file handles (files, sockets).
   * @return maxOpenFiles
  **/
  @ApiModelProperty(value = "Maximum number of open file handles (files, sockets).")
  public Integer getMaxOpenFiles() {
    return maxOpenFiles;
  }

  public void setMaxOpenFiles(Integer maxOpenFiles) {
    this.maxOpenFiles = maxOpenFiles;
  }

  public ConfigInfo maxLoad(Double maxLoad) {
    this.maxLoad = maxLoad;
    return this;
  }

   /**
   * Maximum load avg on system.
   * @return maxLoad
  **/
  @ApiModelProperty(value = "Maximum load avg on system.")
  public Double getMaxLoad() {
    return maxLoad;
  }

  public void setMaxLoad(Double maxLoad) {
    this.maxLoad = maxLoad;
  }

  public ConfigInfo setid(SetId setid) {
    this.setid = setid;
    return this;
  }

   /**
   * Effective user/group id for running Asterisk.
   * @return setid
  **/
  @ApiModelProperty(required = true, value = "Effective user/group id for running Asterisk.")
  public SetId getSetid() {
    return setid;
  }

  public void setSetid(SetId setid) {
    this.setid = setid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigInfo configInfo = (ConfigInfo) o;
    return Objects.equals(this.name, configInfo.name) &&
        Objects.equals(this.defaultLanguage, configInfo.defaultLanguage) &&
        Objects.equals(this.maxChannels, configInfo.maxChannels) &&
        Objects.equals(this.maxOpenFiles, configInfo.maxOpenFiles) &&
        Objects.equals(this.maxLoad, configInfo.maxLoad) &&
        Objects.equals(this.setid, configInfo.setid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, defaultLanguage, maxChannels, maxOpenFiles, maxLoad, setid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigInfo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    defaultLanguage: ").append(toIndentedString(defaultLanguage)).append("\n");
    sb.append("    maxChannels: ").append(toIndentedString(maxChannels)).append("\n");
    sb.append("    maxOpenFiles: ").append(toIndentedString(maxOpenFiles)).append("\n");
    sb.append("    maxLoad: ").append(toIndentedString(maxLoad)).append("\n");
    sb.append("    setid: ").append(toIndentedString(setid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

