/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Dialplan location (context/extension/priority)
 */
@ApiModel(description = "Dialplan location (context/extension/priority)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class DialplanCEP {
  @SerializedName("context")
  private String context = null;

  @SerializedName("exten")
  private String exten = null;

  @SerializedName("priority")
  private Long priority = null;

  public DialplanCEP context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Context in the dialplan
   * @return context
  **/
  @ApiModelProperty(required = true, value = "Context in the dialplan")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public DialplanCEP exten(String exten) {
    this.exten = exten;
    return this;
  }

   /**
   * Extension in the dialplan
   * @return exten
  **/
  @ApiModelProperty(required = true, value = "Extension in the dialplan")
  public String getExten() {
    return exten;
  }

  public void setExten(String exten) {
    this.exten = exten;
  }

  public DialplanCEP priority(Long priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority in the dialplan
   * @return priority
  **/
  @ApiModelProperty(required = true, value = "Priority in the dialplan")
  public Long getPriority() {
    return priority;
  }

  public void setPriority(Long priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DialplanCEP dialplanCEP = (DialplanCEP) o;
    return Objects.equals(this.context, dialplanCEP.context) &&
        Objects.equals(this.exten, dialplanCEP.exten) &&
        Objects.equals(this.priority, dialplanCEP.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, exten, priority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DialplanCEP {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    exten: ").append(toIndentedString(exten)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

