/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Details of an Asterisk log channel
 */
@ApiModel(description = "Details of an Asterisk log channel")

public class LogChannel {
  @SerializedName("channel")
  private String channel = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("configuration")
  private String _configuration = null;

  public LogChannel channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The log channel path
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "The log channel path")
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public LogChannel type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Types of logs for the log channel
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Types of logs for the log channel")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public LogChannel status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Whether or not a log type is enabled
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Whether or not a log type is enabled")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public LogChannel _configuration(String _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * The various log levels
   * @return _configuration
  **/
  @ApiModelProperty(required = true, value = "The various log levels")
  public String getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(String _configuration) {
    this._configuration = _configuration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogChannel logChannel = (LogChannel) o;
    return Objects.equals(this.channel, logChannel.channel) &&
        Objects.equals(this.type, logChannel.type) &&
        Objects.equals(this.status, logChannel.status) &&
        Objects.equals(this._configuration, logChannel._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, type, status, _configuration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogChannel {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

