/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.github.jasterisk.model.Channel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Notification that a channel has entered a Stasis application.
 */
@ApiModel(description = "Notification that a channel has entered a Stasis application.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-02T16:24:17.590+02:00")
public class StasisStart {
  @SerializedName("args")
  private List<String> args = new ArrayList<>();

  @SerializedName("channel")
  private Channel channel = null;

  @SerializedName("replace_channel")
  private Channel replaceChannel = null;

  public StasisStart args(List<String> args) {
    this.args = args;
    return this;
  }

  public StasisStart addArgsItem(String argsItem) {
    this.args.add(argsItem);
    return this;
  }

   /**
   * Arguments to the application
   * @return args
  **/
  @ApiModelProperty(required = true, value = "Arguments to the application")
  public List<String> getArgs() {
    return args;
  }

  public void setArgs(List<String> args) {
    this.args = args;
  }

  public StasisStart channel(Channel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "")
  public Channel getChannel() {
    return channel;
  }

  public void setChannel(Channel channel) {
    this.channel = channel;
  }

  public StasisStart replaceChannel(Channel replaceChannel) {
    this.replaceChannel = replaceChannel;
    return this;
  }

   /**
   * Get replaceChannel
   * @return replaceChannel
  **/
  @ApiModelProperty(value = "")
  public Channel getReplaceChannel() {
    return replaceChannel;
  }

  public void setReplaceChannel(Channel replaceChannel) {
    this.replaceChannel = replaceChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StasisStart stasisStart = (StasisStart) o;
    return Objects.equals(this.args, stasisStart.args) &&
        Objects.equals(this.channel, stasisStart.channel) &&
        Objects.equals(this.replaceChannel, stasisStart.replaceChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, channel, replaceChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StasisStart {\n");
    
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    replaceChannel: ").append(toIndentedString(replaceChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

