/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Info about Asterisk status
 */
@ApiModel(description = "Info about Asterisk status")

public class StatusInfo {
  @SerializedName("startup_time")
  private OffsetDateTime startupTime = null;

  @SerializedName("last_reload_time")
  private OffsetDateTime lastReloadTime = null;

  public StatusInfo startupTime(OffsetDateTime startupTime) {
    this.startupTime = startupTime;
    return this;
  }

   /**
   * Time when Asterisk was started.
   * @return startupTime
  **/
  @ApiModelProperty(required = true, value = "Time when Asterisk was started.")
  public OffsetDateTime getStartupTime() {
    return startupTime;
  }

  public void setStartupTime(OffsetDateTime startupTime) {
    this.startupTime = startupTime;
  }

  public StatusInfo lastReloadTime(OffsetDateTime lastReloadTime) {
    this.lastReloadTime = lastReloadTime;
    return this;
  }

   /**
   * Time when Asterisk was last reloaded.
   * @return lastReloadTime
  **/
  @ApiModelProperty(required = true, value = "Time when Asterisk was last reloaded.")
  public OffsetDateTime getLastReloadTime() {
    return lastReloadTime;
  }

  public void setLastReloadTime(OffsetDateTime lastReloadTime) {
    this.lastReloadTime = lastReloadTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusInfo statusInfo = (StatusInfo) o;
    return Objects.equals(this.startupTime, statusInfo.startupTime) &&
        Objects.equals(this.lastReloadTime, statusInfo.lastReloadTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startupTime, lastReloadTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusInfo {\n");
    
    sb.append("    startupTime: ").append(toIndentedString(startupTime)).append("\n");
    sb.append("    lastReloadTime: ").append(toIndentedString(lastReloadTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

