/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jasterisk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A key/value pair that is part of channel variables.
 */
@ApiModel(description = "A key/value pair that is part of channel variables.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-07T21:43:27.583+02:00")
public class VariableTuple {
  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("variable")
  private String variable = null;

  public VariableTuple endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Channel endpoint.
   * @return endpoint
  **/
  @ApiModelProperty(required = true, value = "Channel endpoint.")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public VariableTuple variable(String variable) {
    this.variable = variable;
    return this;
  }

   /**
   * The value for the variable (json, see documentation).
   * @return variable
  **/
  @ApiModelProperty(required = true, value = "The value for the variable (json, see documentation).")
  public String getVariable() {
    return variable;
  }

  public void setVariable(String variable) {
    this.variable = variable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableTuple variableTuple = (VariableTuple) o;
    return Objects.equals(this.endpoint, variableTuple.endpoint) &&
        Objects.equals(this.variable, variableTuple.variable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoint, variable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableTuple {\n");
    
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    variable: ").append(toIndentedString(variable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

